# Generated by Django 4.1.7 on 2023-03-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password_confirmation', models.CharField(max_length=128)),
            ],
        ),
    ]
